-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS KayttajaHuone CASCADE;
DROP TABLE IF EXISTS Viesti CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Huone CASCADE;
